### ISSUE TITLE
Version 1.2.2 can't work with Bootsnap

### ISSUE THREAD

**Issue by saiqulhaq** [Shopify/memcached_store#45]
my app works fine with 1.2.1

```
/Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant': uninitialized constant ActiveSupport::Cache::MemcachedStore (NameError)
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/memcached_store-1.2.2/lib/memcached_store/railtie.rb:5:in `block in <class:Railtie>'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:347:in `call'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `public_send'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `method_missing'
        from /Users/saiqulhaq/.code/repos/hh/rails-app/config/environment.rb:6:in `<main>'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/saiqulhaq/.rbenv/versions/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

**Comment by rafaelfranca** [comment]
That is true. The railtie is broken given the constant is only going to be loaded when the store is configured. can you send a PR to change the railtie to use `ActiveSupport.on_load(:memcached_store)` and add the `ActiveSupport.run_load_hook(:memcached_store)` to the `ActiveSupport::Cache::MemcachedStore`?
